# Generated by Django 2.1.2 on 2018-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='timestamp',
            field=models.DateTimeField(verbose_name='creation time'),
        ),
    ]
